   apiVersion: v1
   kind: Service
   metadata:
     labels:
       app: gateway
     name: gateway-svc
   spec:
     type: ClusterIP
     selector:
       app: gateway
     ports:
     - name: http-tasktick
       port: 80
       targetPort: http
