 apiVersion: v1
 kind: Service
 metadata:
   labels:
     app: projectmanager
   name: projectmanager-svc
 spec:
   type: ClusterIP
   selector:
     app: projectmanager
   ports:
   - name: pm-http
     port: 9000
     targetPort: http
