    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: tasktick
    spec:
      rules:
      - host: tasktick.io
        http:
          paths: 
          - path: /
            backend:
              serviceName: gateway-svc
              servicePort: 80  
